//Application có mấy state. Nêu ý nghĩa của các function handle application state
import UIKit

var str = "Hello, playground"
//Application có 5 state
//Not running --- App của bạn chưa được chạy hoặc là đang chạy nhưng đã bị hệ thống chấm dứt kết nối (terminated)
//In active --- App đang chạy ở Foreground nhưng không nhận bất kì sự kiện tương tác nào. Nó có thể xảy ra trong trường hợp có cuộc gọi hoặc có tin nhắn tới. App còn có thể ở trạng thái này khi bạn đang trong quá trình chuyển đổi qua các trạng thái khác và chúng ta không thể tương tác bất kì sự kiện nào với UI của app.
//Active --- App đang chạy trên Foreground và nhận các sự kiện tương tác. Đây là một trạng thái bình thường của Foreground apps. Cách duy nhất để để đi tới (hoặc đi từ) trạng thái Active là qua trạng thái Inactive. User thường tương tác với UI 1 cách dễ dàng.
//Background --- App chạy dưới background và vẫn thực thi code. Các ứng dụng mới chạy sẽ lập tức đi qua trạng thái In-Active và sau đó là Active. App nếu như bị đình chỉ(suspended) sẽ quay về trạng thái Background sau đó chuyển sang trạng thái In-Active -> Active. Ngoài ra, app được khởi chạy trực tiếp vào background sẽ chuyển sang trạng thái này thay vì trạng thái In-Active.
//Suspended --- App chạy dưới background nhưng không thực thi code. Hệ thống sẽ tự động chuyển trạng thái của app sang trạng thái và không báo cho chúng ta biết trước. Trong trường hợp thiếu bộ nhớ, hệ thống sẽ lọc và tắt các ứng dụng đang trong trạng thái Suspended để tạo không gian trống cho các ứng dụng khác. Thông thường sau 5s ở dưới background, app sẽ chuyển trạng thái sang Suspended nhưng chúng ta có thể nới rộng thời gian ấy ra nếu như muốn.
//application:willFinishLaunchingWithOptions --- Method này sẽ được gọi sau khi app của bạn đã khởi chạy thành công. Đây là method đầu tiên được gọi trong AppDelegate. Bạn có thể thực thi code trong hàm này khi việc khởi chạy đã hoàn thành.
//application:didFinishLaunchingWithOptions --- Method này được gọi trước khi window của app được hiển thị. Bạn có thể hoàn thiện giao diện của mình và cung cấp root viewcontroller cho window.
//applicationDidBecomeActive --- Method này được gọi để báo cho app của bạn biết khi nó chuyển trạng thái từ In-Active sang Activehoặc hệ thống và user khơi động app hoặc trong trường hợp user bỏ quan các gián đoạn làm app ngay lập tức chuyển sang In-Active(như là huỷ cuộc gọi hoặc tin nhắn). Bạn nên dùng method này để chạy lại các tác vụ đang bị dừng(hoặc chưa chạy) khi app bắt đầu chạy lại.
//applicationWillResignActive  --- Method này được gọi để báo cho app biết rằng nó sắp chuyển từ trạng thái Active sang In-Active . Nó xãy ra khi trường hợp bị gián đoạn (có cuộc gọi tới hoặc SMS hoặc báo thức) hay là khi user tắt app đi.
//applicationDidEnterBackground  --- Method này được gọi để báo cho app biết nó đang không chạy ở dưới foreground. Bạn có khoảng tầm 5 giây để thực thi các task . Trong trường hợp bạn muốn có nhiều thời gian hơn để xử lý, bạn có thể yêu cầu hệ thống cấp cho thời gian thực thi bằng cách gọi hàm beginBackgroundTask(expirationHandler:) . Nếu như method không được thực thi và trả về trước thời gian hết hạn thì app sẽ bị hệ thống chấm dứt và xoá khỏi bộ nhớ.
//applicationWillEnterForeground --- Method này được gọi như là 1 phần trong việc chuyển trạng thái từ Background sang Active. Bạn nên dùng method này để hoàn thành các thay đổi đối với app trước khi nó xuống Background. applicationDidBecomeActive sẽ được gọi ngay khi method này đã hoàn thành việc chuyển trạng thái của app từ In-Active sang Active.
//applicationWillTerminate  --- Method này được gọi khi app của bạn sắp bị hệ thống khai tử khỏi bộ nhớ. Bạn nên dùng method này để thực thi các tác vụ dọn dẹp. Nếu hàm của bạn không trả về trước thời gian hết hạn, hệ thống sẽ tự động khai tử app kèm cả task đang thực thi của bạn khỏi bộ nhớ. Method này cũng được gọi trong trường hợp app đang chạy ở dưới background( không bị suspended) nhưng hệ thống lại cần phải huỷ nó vì vài lí do gì đó. không nên đợi applicationWillTerminate được gọi rồi mới lưu lại data. Trong 1 vài trường hợp hi hữu, applicationWillTerminate sẽ không được gọi trước khi app bị khai tử (Vd như trong trường hợp máy của bạn reboot lại thì method này sẽ không được gọi).
