# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movie 2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Movie 2
	  pod 'FSPagerView'
	  pod 'HCSStarRatingView', '~> 1.5'
  	pod 'FaveButton'
  	pod 'RealmSwift', '~> 5.5.0'
    end
